version: "3.4"
services:
  frontend:
    image: node:alpine
    container_name: eva-app
    entrypoint: /bin/sh
    ports:
      - 8080:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true